/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiAgentChatIdStreamRouteImport } from './routes/api/agent/$chatId/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentChatIdStreamRoute = ApiAgentChatIdStreamRouteImport.update({
  id: '/$chatId/stream',
  path: '/$chatId/stream',
  getParentRoute: () => ApiAgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/agent/$chatId/stream': typeof ApiAgentChatIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/agent/$chatId/stream': typeof ApiAgentChatIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/agent/$chatId/stream': typeof ApiAgentChatIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agent'
    | '/project/$projectId'
    | '/rpc/$'
    | '/api/agent/$chatId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agent'
    | '/project/$projectId'
    | '/rpc/$'
    | '/api/agent/$chatId/stream'
  id:
    | '__root__'
    | '/'
    | '/api/agent'
    | '/project/$projectId'
    | '/rpc/$'
    | '/api/agent/$chatId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  RpcSplatRoute: typeof RpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$chatId/stream': {
      id: '/api/agent/$chatId/stream'
      path: '/$chatId/stream'
      fullPath: '/api/agent/$chatId/stream'
      preLoaderRoute: typeof ApiAgentChatIdStreamRouteImport
      parentRoute: typeof ApiAgentRoute
    }
  }
}

interface ApiAgentRouteChildren {
  ApiAgentChatIdStreamRoute: typeof ApiAgentChatIdStreamRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentChatIdStreamRoute: ApiAgentChatIdStreamRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  RpcSplatRoute: RpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
